config/routes.rb
Rails.application.routes.draw do

  resources :wikis do 
    resources :collaborations, only: [:create, :destroy]
  end
  
  resources :charges, only: [:new, :create, :update]
  

  get 'about' => 'welcome#about'

  get 'downgrade' => 'charges#update' #Interesting construct.  Did not know you could create your own routes with a specific method.
  
  devise_for :users, controllers: { registrations: "registrations" }
  root :to=>"welcome#index"

end

app/models/wiki.rb
# == Schema Information
#
# Table name: wikis
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  private    :boolean          default(FALSE)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations

  scope :visible_to, -> (user) { user ? all : where(private: false) }
  default_scope { order('created_at DESC') }
  
  def public?
    !private
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    # @wikis = Wiki.visible_to(current_user).all
    @wikis = policy_scope(Wiki)

  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    # @wiki=Wiki.new(params.require(:wiki).permit(:title, :body))
    # Had problems creating the new Wiki above as no user associated to a new Wiki
    # Need to either add @wiki.user = current_user
    # Or the solution below
    
    @wiki = current_user.wikis.build(wiki_params)
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the post.  Please try again."
      render :new
    end

  end

  def edit
    @wiki = Wiki.find(params[:id])
    @collaborations = @wiki.collaborations
    @collaboration = Collaboration.new
    @users = User.all.to_a.reject!{|x| @collaborations.users.include?(x) || @wiki.user == x}
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the Wiki.  Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "The \"#{@wiki.title}\" Wiki was deleted successfully."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<script src="epiceditor.min.js"></script>

<body>
  <div id="epiceditor"></div>
</body>
<script type="text/javascript">
  var editor = new EpicEditor().load();
</script>


<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: "Enter Wiki title" %>
  </div>
  
  <div class="form-group" id="epiceditor">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
  </div>
  
  <% if current_user.role == 'admin' || (current_user.role == 'premium' && current_user.id == wiki.user_id)%>
  <div class="form-group pull-right text-danger">
    <%= f.label :private, class: 'checkbox' do %>
    <%= f.check_box :private %> Private Wiki
    <% end %>
  </div>
  <% end %>
  
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

<%end%>

<!-- ~~~~~~~~~~~ -->
<div id="epiceditor"> <textarea name="content" id="id_content"></textarea> </div>
<!-- ~~~~~~~~~~~ -->
<div id="container">
  <iframe id="epiceditor-instance-id">
    <html>
      <head>
        <link type="text/css" id="" rel="stylesheet" href="epiceditor/themes/base/epiceditor.css" media="screen">
      </head>
      <body>
        <div id="epiceditor-wrapper">
          <iframe id="epiceditor-editor-frame">
            <html>
              <head>
                <link type="text/css" rel="stylesheet" href="epiceditor/themes/editor/epic-dark.css" media="screen">
              </head>
              <body contenteditable="true">
                <!-- raw content -->
              </body>
            </html>
          </iframe>
          <iframe id="epiceditor-previewer-frame">
            <html>
              <head>
                <link type="text/css" rel="stylesheet" href="epiceditor/themes/preview/github.css" media="screen">
              </head>
              <body>
                <div id="epiceditor-preview">
                  <!-- rendered html -->
                </div>
              </body>
            </html>
          </iframe>
          <div id="epiceditor-utilbar">
            <span title="Toggle Preview Mode" class="epiceditor-toggle-btn epiceditor-toggle-preview-btn"></span>
            <span title="Enter Fullscreen" class="epiceditor-fullscreen-btn"></span>
          </div>
        </div>
      </body>
    </html>
  </iframe>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Wikis</p>
    <ul>
      <li>Make sure you enter a title</li>
      <li>Make sure your Wiki is factually correct</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals:{wiki: @wiki} %>
  </div>  
</div>
<br/>

<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-8">
    <% if !@collaborations.blank? %>
      <h4>Collaborators</h4>

      <% @collaborations.each do |c| %>
        <p>
          <%= link_to wiki_collaboration_path(@wiki, c), method: :delete do %>
            <span class="glyphicon glyphicon-remove-circle"></span>
          <%end%>
          <%= c.user.name %>
        </p>
      <%end%>
    <% end %>
    <br/>

    <%= form_for [@wiki, @collaboration] do |f| %>
      <h4><%= f.label :user_id, 'Add New Collaborators' %></h4>
      <%= f.collection_select(:user_id, @users, :id, :name) %><br/><br/>
      <%= f.submit class: 'btn btn-success' %>
    <%end%>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <% if (!wiki.private? || (wiki.private? && current_user.id == wiki.user_id) || current_user.admin?) %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <p><%= link_to (markdown_to_html wiki.title), wiki %><% if wiki.private?%> <span class="badge"> Private</span><%end%></p>
            </h4>

            <small>
            Created by: <%=  wiki.user.name %> <%= time_ago_in_words(wiki.created_at) %> ago
            | <%= link_to "Delete", wiki, method: :delete, data: {confirm: 'Are you sure you want to delete this Wiki?'} %>
          </small>

          </div>
        </div>
      <%end%>
    <%end%>
  </div>

  <div class="col-md-4">
    <% if policy(Wiki.new).create? %>
      <%= link_to "Create New Wiki", new_wiki_path(@wiki), class: 'btn btn-success pull-right' %>
    <% end %>
  </div>

</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Wikis</p>
    <ul>
      <li>Make sure you enter a title</li>
      <li>Make sure your Wiki is factually correct</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: "Enter Wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>

    <%end%>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title%></h1>

<div class = "row">
  
  <div class="col-md-8">
    <p><%= markdown_to_html @wiki.body%></p>
  </div>

  <div class="col-md-4">
    
    <% if policy(@wiki).edit? %>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success pull-right edit-btn' %>
    <% end %>
    
    <% if policy(@wiki).destroy? %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger pull-right', data: {confirm: 'Are you sure you want to delete this Wiki?'} %>
    <% end %>
  </div>
  

</div>