config/routes.rb
Rails.application.routes.draw do

  resources :wikis do 
    resources :collaborations, only: [:create, :destroy]
  end
  
  resources :charges, only: [:new, :create, :update]
  

  get 'about' => 'welcome#about'

  get 'downgrade' => 'charges#update' #Interesting construct.  Did not know you could create your own routes with a specific method.
  
  devise_for :users, controllers: { registrations: "registrations" }
  root :to=>"welcome#index"

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

class Amount
  def self.default
    200
  end
end

def create
  #Creates a Stripe Customer object, for associating with the charge
  
  customer = Stripe::Customer.create(
    email: current_user.email, 
    card: params[:stripeToken])

  #Where the real magic happens?
  charge = Stripe::Charge.create(
    customer: customer.id, # Note -- this is not the user_id in your app
    amount: Amount.default,
    description: "BigMoney Membership - #{current_user.email}",
    currency: 'usd'
    )

  flash[:notice] = "Thank you #{current_user.email}.  Your payment has been recieved."
  current_user.upgrade_acct
  redirect_to edit_user_registration_path

  # Stripe will send back CardErrors, with friendly messages when something goes wrong.  This 'rescue block' catches and displays those errors.

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

def new
  @stripe_btn_data = {
    key: "#{Rails.configuration.stripe[:publishable_key]}",
    description: "BigMoney Membership - #{current_user.name}",
    amount: Amount.default
  }
end

def update
  current_user.downgrade_acct
  redirect_to edit_user_registration_path
end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/new.html.erb
<% if current_user.premium? %>
  <h1 class="text-primary">Cancelation Confirmation</h1>
    <h4>Please confirm you really would like to cancel.  You will miss out on the following benefits.</h4>
    <ul>
      <li>Create unlimited public wikis</li>
      <li>Collaborate with unlimited users</li>
    </ul>
    <p>Cancelling your premium membership will also result in your Private Wikis being converted to Public Wikis.</p>
    <div>
      <%= link_to "Confirm", downgrade_path, class: 'btn btn-info'%>
    </div>

<%else%>
  <%= form_tag charges_path do %>
    
    <h4>Payment Confirmation</h4>
    <p>Please click the button below to enter payment information and complete the upgrade to your premium membership"</p>
    <script 
      class='stripe-button' 
      src="https://checkout.stripe.com/checkout.js" 
      data-key="<%=@stripe_btn_data[:key] %>" 
      data-amount=<%= @stripe_btn_data[:amount]%> 
      data-description="<%= @stripe_btn_data[:description] %>" >
    </script>

  <% end %>
<%end%>