config/routes.rb
Rails.application.routes.draw do

  resources :wikis do 
    resources :collaborations, only: [:create, :destroy]
  end
  
  resources :charges, only: [:new, :create, :update]
  

  get 'about' => 'welcome#about'

  get 'downgrade' => 'charges#update' #Interesting construct.  Did not know you could create your own routes with a specific method.
  
  devise_for :users, controllers: { registrations: "registrations" }
  root :to=>"welcome#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>

        <div class="pull-right user-info">
          <% if current_user %>
            Hello <%= link_to current_user.name, edit_user_registration_path %> |
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>

          <%if current_user %>
            <% if current_user.premium? %>
              | <span class="badge">Premium Member</span>
            <% elsif current_user.admin? %>
              | <span class="badge">Administrator</span>
            <%end%>
          <%end%>
        </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>